In [14]:
import numpy as np
import math
import random

In [15]:
row=int(input("Enter row size:"))
col=int(input("Enter col size:"))

Enter row size:3
Enter col size:4


In [16]:
entries=list(map(int,input().split()))

1 2 3 4 5 6 7 8 9 0 1 2


In [20]:
arr1=np.array(entries).reshape(row,col)

In [21]:
arr2=np.array(random.sample(range(0,100),12))

In [35]:
arr2=arr2.reshape(col,row)
print(arr1)
print(arr2)
print(np.shape(arr1))

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]
[[50 31 25]
 [88 22  8]
 [ 3 67 54]
 [46 82 70]]
(3, 4)


In [36]:
np.matmul(arr1,arr2)

array([[ 419,  604,  483],
       [1167, 1412, 1111],
       [ 545,  510,  419]])

In [37]:
arr2=arr2.reshape(row,col)

In [39]:
result=arr1+arr2

In [40]:
print(result)

[[51 33 28 92]
 [27 14 10 75]
 [63 46 83 72]]


In [43]:
print(result.T)

[[51 27 63]
 [33 14 46]
 [28 10 83]
 [92 75 72]]


In [62]:
result=result.reshape(12,)

In [66]:
result=result[:9].reshape(3,3)

In [67]:
np.linalg.det(result)

32193.000000000025

In [68]:
np.linalg.inv(result)

array([[ 0.02022179,  0.00065232, -0.00913242],
       [-0.17569037,  0.09110676,  0.05783866],
       [ 0.20594539, -0.10856397, -0.05153294]])